version: "3.7"
services:
  state-api-dev:
    container_name: state-api-dev
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/usr/src/app/src
