apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: opentransit-state-api
  name: opentransit-state-api
spec:
  selector:
    matchLabels:
      run: opentransit-state-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: opentransit-state-api
    spec:
      containers:
      - image: gcr.io/YOUR_GCP_PROJECT_ID/opentransit-state-api:latest
        imagePullPolicy: IfNotPresent
        name: opentransit-state-api
        resources:
          requests:
            cpu: 0.03
        env:
          - name: OPENTRANSIT_S3_BUCKET
            value: YOUR_OPENTRANSIT_S3_BUCKET
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws_secret_access_key
