apiVersion: v1
kind: Service
metadata:
  labels:
    run: opentransit-state-api
  name: opentransit-state-api
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 4000
  selector:
    run: opentransit-state-api
  type: LoadBalancer
